# Generated by Django 4.0.4 on 2022-05-23 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=16, unique=True)),
                ('ccv', models.IntegerField()),
                ('money', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'bankcards',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('type', models.CharField(max_length=20)),
                ('wheel_size', models.IntegerField()),
                ('fork', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image1', models.ImageField(upload_to='images/bicycles/%Y/%m/%d/')),
                ('image2', models.ImageField(upload_to='images/bicycles/%Y/%m/%d/')),
                ('image3', models.ImageField(upload_to='images/bicycles/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'bicycles',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(default='images/profiles/avatar.png', upload_to='images/%Y/%m/%d/')),
                ('bank_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.bankcard', to_field='num')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='RentingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_get', models.DateTimeField()),
                ('time_return', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
                ('bicycle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.bicycle')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.AddField(
            model_name='bicycle',
            name='renting_users',
            field=models.ManyToManyField(related_name='bicycles', through='api.RentingInfo', to='api.user'),
        ),
    ]
