# Generated by Django 4.0.4 on 2022-05-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bicycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('wheel_size', models.IntegerField()),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('image1', models.ImageField(upload_to='images/bicycles/%Y/%m/%d/')),
                ('image2', models.ImageField(upload_to='images/bicycles/%Y/%m/%d/')),
                ('image3', models.ImageField(upload_to='images/bicycles/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=100)),
                ('date_birthday', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=40)),
                ('card_num', models.IntegerField()),
                ('card_date', models.DateTimeField(auto_now=True)),
                ('card_ccv', models.IntegerField()),
                ('profile_photo', models.ImageField(default='images/profiles/avatar.png', upload_to='images/%Y/%m/%d/')),
            ],
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
