# Generated by Django 4.0.4 on 2022-05-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='image1',
            field=models.ImageField(upload_to='images/bicycles/'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='image2',
            field=models.ImageField(upload_to='images/bicycles/'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='image3',
            field=models.ImageField(upload_to='images/bicycles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='static/images/avatar.png', upload_to='images/avatars'),
        ),
    ]
