# Generated by Django 4.0.4 on 2022-05-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bicycle_image1_alter_bicycle_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
