# Generated by Django 4.0.4 on 2022-05-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_account_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=16, unique=True)),
                ('ccv', models.IntegerField()),
                ('money', models.IntegerField()),
            ],
            options={
                'db_table': 'bankcards',
                'ordering': ['num'],
            },
        ),
        migrations.CreateModel(
            name='RentingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_get', models.DateTimeField()),
                ('time_return', models.DateTimeField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('telephone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(default='images/profiles/avatar.png', upload_to='images/%Y/%m/%d/')),
                ('bank_card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.bankcard', to_field='num')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AlterModelOptions(
            name='bicycle',
            options={'ordering': ['brand', 'model']},
        ),
        migrations.AddField(
            model_name='bicycle',
            name='fork',
            field=models.CharField(default='rock shox', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='model',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='bicycle',
            table='bicycles',
        ),
        migrations.AddField(
            model_name='rentinginfo',
            name='bicycle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.bicycle'),
        ),
        migrations.AddField(
            model_name='rentinginfo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='bicycle',
            name='renting_users',
            field=models.ManyToManyField(related_name='bicycles', through='api.RentingInfo', to='api.user'),
        ),
    ]
