# Generated by Django 4.0.4 on 2022-05-25 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='images/avatar.jpg', upload_to='images/avatars/'),
        ),
    ]
