# Generated by Django 4.0.4 on 2022-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='images/bicycles/avatar.jpg', upload_to='images/avatars/'),
        ),
    ]
