# Generated by Django 4.0.4 on 2022-05-26 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0005_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bank_card',
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='renting_users',
            field=models.ManyToManyField(related_name='bicycles', through='api.RentingInfo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentinginfo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BankCard',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
