# Generated by Django 4.0.4 on 2022-06-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rentinginfo_total_price_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL'),
        ),
    ]
