# Generated by Django 4.0.4 on 2022-06-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_bicycle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bicycle',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images/bicycles/'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/bicycles/'),
        ),
        migrations.AlterField(
            model_name='bicycle',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/bicycles/'),
        ),
    ]
