# Generated by Django 4.0.4 on 2022-06-06 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_alter_rentinginfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinginfo',
            name='bicycle',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='api.bicycle'),
        ),
        migrations.AlterField(
            model_name='rentinginfo',
            name='user',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rents', to=settings.AUTH_USER_MODEL),
        ),
    ]
